import Head from 'next/head';
import React from 'react';
import styles from '../styles/Home.module.css';
import nextPackage from 'next/package.json';

export default function Home({}) {
  return (
    <div>
      <Head>
        <title>Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/../../public/main.css" rel="stylesheet"></link>
      </Head>

      <main>
        <h1 className="p-20">
          Welcome to <a href="https://nextjs.org">Next.js!</a> v
          {nextPackage.version}
        </h1>

        <p>
          Get started by editing <code>pages/index.tsx</code>
        </p>
      </main>
    </div>
  );
}
